In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
%matplotlib inline

In [3]:
df = pd.read_csv(r"C:\Users\Anisha Ray\Downloads\py-master\ML\2_linear_reg_multivariate\homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
#since number of bedrooms for 3rd index is missing, median of all other bedrooms will be taken and replaced there
import math
median_bedrooms= math.floor(df.bedrooms.median())
median_bedrooms

3

In [8]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)  #fillna function in pandas series used to put a value in place of missing ones
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [10]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [11]:
reg.intercept_

383725.0

In [12]:
reg.predict([[3000,3,40]])

array([444400.])

In [15]:
reg.predict([[2500,4,5]])

array([588625.])